services:
  stac-dev:
    image: pc-apis-stac-dev
    build:
      context: .
      dockerfile: pcstac/Dockerfile.dev
    environment:
      - ENVIRONMENT=development
      - POSTGRES_USER=username
      - POSTGRES_PASS=password
      - POSTGRES_DBNAME=postgis
      - POSTGRES_HOST=database
      - POSTGRES_HOST_READER=database
      - POSTGRES_HOST_WRITER=database
      - POSTGRES_PORT=5432
    volumes:
      - .:/opt/src
    command: >
      /bin/bash
    depends_on:
      - stac
  tiler-dev:
    image: pc-apis-tiler-dev
    # For Mac OS M1 user, you'll need to add `platform: linux/amd64`.
    # see https://github.com/developmentseed/titiler/discussions/387#discussioncomment-1643110
    # platform: linux/amd64
    build:
      context: .
      dockerfile: pctiler/Dockerfile.dev
    environment:
      - ENVIRONMENT=development
      - FF_VRT="yes"
      - STAC_API_URL=http://stac:8081
      - STAC_API_HREF=http://localhost:8080/stac/

      # titiler.pgstac
      - POSTGRES_USER=username
      - POSTGRES_PASS=password
      - POSTGRES_DBNAME=postgis
      - POSTGRES_HOST=database
      - POSTGRES_HOST_READER=database
      - POSTGRES_HOST_WRITER=database
      - POSTGRES_PORT=5432
      - WEB_CONCURRENCY=1
      - WORKERS_PER_CORE=1
    volumes:
      - .:/opt/src
    command: >
      /bin/bash
    depends_on:
      - stac
      - tiler
