{{- if .Values.pcingress.certIssuer.enabled -}}
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: {{ .Values.pcingress.certIssuer.privateKeySecretRef }}-pcingress
spec:
  acme:
    server: {{ .Values.pcingress.certIssuer.server }}
    email: {{ .Values.pcingress.certIssuer.issuerEmail }}
    privateKeySecretRef:
      name: {{ .Values.pcingress.certIssuer.privateKeySecretRef }}
    solvers:
    - http01:
        ingress:
          class: nginx
          podTemplate:
            spec:
              nodeSelector:
                "kubernetes.io/os": linux
{{- end }}